volumes:
  my-datavolume:
  
services:
  db:
    image: mysql
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: autofirmdb
    networks:
      - my-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5266:8080"
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my-network

networks:
  my-network:
    

